const fs = require("fs");
["lib/esm", "lib/cjs"].forEach((buildPath) => {
  fs.copyFileSync(
    `src/safecoin/core/bridge_bg.wasm`,
    `${buildPath}/safecoin/core/bridge_bg.wasm`
  );
  fs.copyFileSync(
    `src/safecoin/core-node/bridge_bg.wasm`,
    `${buildPath}/safecoin/core-node/bridge_bg.wasm`
  );
  fs.copyFileSync(
    `src/safecoin/core/bridge_bg.wasm.d.ts`,
    `${buildPath}/safecoin/core/bridge_bg.wasm.d.ts`
  );
  fs.copyFileSync(
    `src/safecoin/core-node/bridge_bg.wasm.d.ts`,
    `${buildPath}/safecoin/core-node/bridge_bg.wasm.d.ts`
  );
  fs.copyFileSync(
    `src/safecoin/nft/nft_bridge_bg.wasm`,
    `${buildPath}/safecoin/nft/nft_bridge_bg.wasm`
  );
  fs.copyFileSync(
    `src/safecoin/nft-node/nft_bridge_bg.wasm`,
    `${buildPath}/safecoin/nft-node/nft_bridge_bg.wasm`
  );
  fs.copyFileSync(
    `src/safecoin/nft/nft_bridge_bg.wasm.d.ts`,
    `${buildPath}/safecoin/nft/nft_bridge_bg.wasm.d.ts`
  );
  fs.copyFileSync(
    `src/safecoin/nft-node/nft_bridge_bg.wasm.d.ts`,
    `${buildPath}/safecoin/nft-node/nft_bridge_bg.wasm.d.ts`
  );
  fs.copyFileSync(
    `src/safecoin/token/token_bridge_bg.wasm`,
    `${buildPath}/safecoin/token/token_bridge_bg.wasm`
  );
  fs.copyFileSync(
    `src/safecoin/token-node/token_bridge_bg.wasm`,
    `${buildPath}/safecoin/token-node/token_bridge_bg.wasm`
  );
  fs.copyFileSync(
    `src/safecoin/token/token_bridge_bg.wasm.d.ts`,
    `${buildPath}/safecoin/token/token_bridge_bg.wasm.d.ts`
  );
  fs.copyFileSync(
    `src/safecoin/token-node/token_bridge_bg.wasm.d.ts`,
    `${buildPath}/safecoin/token-node/token_bridge_bg.wasm.d.ts`
  );
  fs.copyFileSync(
    `src/safecoin/migration/wormhole_migration_bg.wasm`,
    `${buildPath}/safecoin/migration/wormhole_migration_bg.wasm`
  );
  fs.copyFileSync(
    `src/safecoin/migration-node/wormhole_migration_bg.wasm`,
    `${buildPath}/safecoin/migration-node/wormhole_migration_bg.wasm`
  );
  fs.copyFileSync(
    `src/safecoin/migration/wormhole_migration_bg.wasm.d.ts`,
    `${buildPath}/safecoin/migration/wormhole_migration_bg.wasm.d.ts`
  );
  fs.copyFileSync(
    `src/safecoin/migration-node/wormhole_migration_bg.wasm.d.ts`,
    `${buildPath}/safecoin/migration-node/wormhole_migration_bg.wasm.d.ts`
  );
});
